// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0NvUyKA8IvVHDxAJSE1CzzlG3uXXrb4o',
    appId: '1:256138182684:web:c585da91389ca5b7f51fd9',
    messagingSenderId: '256138182684',
    projectId: 'cityguard-d1890',
    authDomain: 'cityguard-d1890.firebaseapp.com',
    storageBucket: 'cityguard-d1890.firebasestorage.app',
    measurementId: 'G-CXD419KFGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2ZmXQzvYbbjz5SdKJparddG1sc__XSM0',
    appId: '1:256138182684:android:15b4d8bfae2265c5f51fd9',
    messagingSenderId: '256138182684',
    projectId: 'cityguard-d1890',
    storageBucket: 'cityguard-d1890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbCShjs5bWW63WVT_oAEPy922bA0HOqxM',
    appId: '1:256138182684:ios:6ff9a9eaa7d45cd0f51fd9',
    messagingSenderId: '256138182684',
    projectId: 'cityguard-d1890',
    storageBucket: 'cityguard-d1890.firebasestorage.app',
    iosBundleId: 'com.example.kitahack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbCShjs5bWW63WVT_oAEPy922bA0HOqxM',
    appId: '1:256138182684:ios:6ff9a9eaa7d45cd0f51fd9',
    messagingSenderId: '256138182684',
    projectId: 'cityguard-d1890',
    storageBucket: 'cityguard-d1890.firebasestorage.app',
    iosBundleId: 'com.example.kitahack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0NvUyKA8IvVHDxAJSE1CzzlG3uXXrb4o',
    appId: '1:256138182684:web:c2928d45f492c99df51fd9',
    messagingSenderId: '256138182684',
    projectId: 'cityguard-d1890',
    authDomain: 'cityguard-d1890.firebaseapp.com',
    storageBucket: 'cityguard-d1890.firebasestorage.app',
    measurementId: 'G-6MN9376VF0',
  );
}
